### ISSUE TITLE
run watobo get error:

### ISSUE THREAD

**Issue by Tide00** [siberas/watobo#15]
I run  watobo and  input "https://www.google.com"in firefox , then get the erros: 

:port: 8081
:proxy_mode: 2
:bind_addr: 127.0.0.1
CREATE NEW CERTIFICATE FOR >> http://www.google.com:443www.google.com:443 <<
CN=http://www.google.com:443www.google.com
! Could not write keypair
No such file or directory @ rb_sysopen - ~/.watobo/CA/fake_certs/http://www.google.com:443www.google.com_keypair.pem

**Comment by siberas** [comment]
what operating system do you use?
did you install watobo from the git repo?

**Comment by Tide00** [comment]
My system is kali rolling. I had install watobo  from  git , and also install it  form kali rolling soucelist.  I had get the same issue.  It seems that "http" web  is ok,  but "https" web get the errors above.

**Comment by Tide00** [comment]
Sorry,  it is due to my wrong configuration. Thank you for your answer.
