### ISSUE TITLE
Watobo automatically closes when I scan an IP address

### ISSUE THREAD

**Issue by suhas-s-dev** [siberas/watobo#16]
The application in the CLI closes everytime it opens and I give an IP address to scan.

**Comment by siberas** [comment]
hi suhas,
thank you for the information. To find a solution I need some more details:
- What OS do you use?
- What ruby version (ruby -v)?
- What is the console output?
- Where do you give an IP address? 

There's also a little video tutorial http://watobo.sourceforge.net/Videos/watobo-crawler_ipad.mp4 which shows the initial usage of watobo.
