### ISSUE TITLE
watobo fails to start (ArgumentError)

### ISSUE THREAD

**Issue by sbrun** [siberas/watobo#5]
Hello,
I'm trying to update the watobo package in Kali (the current package in Kali is broken).
But I have this issue:
```
/var/lib/gems/2.3.0/gems/fxruby-1.6.29/lib/fox16/kwargs.rb:972:in `initialize': wrong number of arguments (given 8, expected 0) (ArgumentError)
```

I have the same issue when installing the gems in a fresh install of kali-rolling:
```
$ apt install g++ libxrandr-dev libfox-1.6-dev
[...]
$ gem install watobo
[...]
$ gem install selenium-driver
[...]
$ watobo
#############################################################

     W A T O B O - THE Web Application Toolbox
     brought to you by siberas http://www.siberas.de

#############################################################
NFQUEUE not available on this system
---
uninitialized constant Watobo::Modules::Active::Sap::Business_objects
when loading module file /var/lib/gems/2.3.0/gems/watobo-0.9.23/modules/active/sap/business_objects.rb
---

Loading FXRuby ... this may take some time ... [OK]
Ruby Version: 2.3.3
Ruby Platform: x86_64-linux-gnu
FXRuby Version: 1.6.29
Fox Version: 1.6.53
Watobo Version: 0.9.23
>> Starting GUI ...
/var/lib/gems/2.3.0/gems/fxruby-1.6.29/lib/fox16/kwargs.rb:972:in `initialize': wrong number of arguments (given 8, expected 0) (ArgumentError)
        from /var/lib/gems/2.3.0/gems/fxruby-1.6.29/lib/fox16/kwargs.rb:972:in `initialize'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/html_viewer.rb:26:in `initialize'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/html_viewer.rb:147:in `new'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/html_viewer.rb:147:in `initialize'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/chatviewer_frame.rb:436:in `new'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/chatviewer_frame.rb:436:in `initialize'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/main_window.rb:1678:in `new'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui/main_window.rb:1678:in `initialize'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui.rb:64:in `new'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/lib/watobo/gui.rb:64:in `start'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/bin/watobo_gui.rb:21:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/watobo-0.9.23/bin/watobo:9:in `<top (required)>'
        from /usr/local/bin/watobo:22:in `load'
        from /usr/local/bin/watobo:22:in `<main>'
```
(it fails even if nfqueue is installed)

**Comment by siberas** [comment]
Hi,

it seems you didn't have installed fxscintilla.
please check out this blogpost http://www.siberas.de/blog/2013/03/18/installing-fxruby-on-kali-linux.html
on how to install fxscintilla.

hope this helps,

/andy

**Comment by sbrun** [comment]
Hi,
Thank you for your answer. Yes, fxscintilla was missing.
Now I'm able to have watobo on Kali with the gems. I'm still working on installable packages for Kali which is not easy (especially for fxruby, watobo is not a problem).

**Comment by siberas** [comment]
Hi, the best way I experienced is to use rvm to create a whole environment. You can find an example here https://sourceforge.net/projects/watobo/files/Debian%20Packages/.
If you have any questions or need some more infos, data (e.g. logos) please let me know. I would really appreciate if watobo would become a fix component of kali.

**Comment by sbrun** [comment]
Hi,
using rvm is not really an option when packaging. But I found a solution to make fxruby work.
watobo version 0.9.23-0kali2 is now in kali-rolling.

**Comment by siberas** [comment]
ok, great!
What's the regular way to support you in packaging?
E.g. I would like to have an AppIcon, or regular updates via git.
Do you have a best-practice guide?

**Comment by sbrun** [comment]
Hi,
There is a guide for "upstream" in Debian: https://wiki.debian.org/UpstreamGuide 
The most important section for Kali is the section about git. If you make tagged releases, we can monitor them and update the package accordingly.
About the AppIcon: if you are thinking about a menu entry in Kali, you can open a bug report in kali.
