### ISSUE TITLE
Watobo crashes in comment function

### ISSUE THREAD

**Issue by h0ng10** [siberas/watobo#6]
When I try to add a comment (via shortcut or by using the menu function), watobo crashes.

Output from the command line
```
FXComposeContext: illegal window parameter
Aborted

```

**Comment by andyschmidt** [comment]
Mmmm ... could not reproduce it. Tested it on Win and Linux without a crash. Do you have more information about your setup? E.g. if you start it in the console you should see something like 

```
Loading FXRuby ... this may take some time ... [OK]
Ruby Version: 2.2.3
Ruby Platform: i386-mingw32
FXRuby Version: 1.6.29
Fox Version: 1.6.49
Watobo Version: 0.9.24pre
>> Starting GUI ...
```

**Comment by andyschmidt** [comment]
ok, I could reproduce it on Ubuntu 16.04 and 15.10. It doesn't crash on Win or Fedora 24/25. Doesn't make any sense to me. Need some more investigation.

**Comment by andyschmidt** [comment]
reduced the crash to a small sample and reported it to the fxruby project site https://github.com/larskanis/fxruby/issues/40

**Comment by andyschmidt** [comment]
I disabled the responsible function, so watobo doesn't crash. Sadly you have to manually click inside the text field to enter your comment.
