### ISSUE TITLE
watobo crashes in sqlmap plugin

### ISSUE THREAD

**Issue by h0ng10** [siberas/watobo#7]
I get a crash when i try to use the sqlmap plugin. It happens when i try to start the sqlmap scan.

watobo output:

```
Start SQLMap with file /home/h0ng10/.watobo/tmp/sqlmap/sqlmap_1494332696.req
/home/h0ng10/watobo/plugins/sqlmap/gui/main.rb:197:in `system': no implicit conversion of false into String (TypeError)
	from /home/h0ng10/watobo/plugins/sqlmap/gui/main.rb:197:in `block in run_sqlmap'
```

**Comment by andyschmidt** [comment]
confirmed. problem is the missing xterm package. Installing xterm will fix the crash.
Xterm will be mandatory in future. I will implement a (better) check function to not make watobo crash and inform the user.
